import { COLUMN_SIZE, COLUMN_STYLE } from "@/app/_const/cols";
import { ColDef } from "ag-grid-community";

export const GRID_COLS: ColDef[] = [
  {
    field: "회사 코드",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "체결 일자",
    width: COLUMN_SIZE.lg,
    resizable: true,
    editable: true,
  },
  {
    field: "체결 일련번호",
    width: COLUMN_SIZE.sm,
    resizable: true,
    editable: true,
    cellStyle: COLUMN_STYLE.right,
  },
  {
    field: "주문 일자",
    width: COLUMN_SIZE.lg,
    resizable: true,
    editable: true,
    cellStyle: COLUMN_STYLE.left,
  },
  {
    field: "주문 일련번호",
    width: COLUMN_SIZE.sm,
    resizable: true,
    editable: true,
  },
  {
    field: "계좌 번호",
    width: COLUMN_SIZE.lg,
    resizable: true,
    editable: true,
  },
  {
    field: "종목 코드",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "매수매도 구분",
    width: COLUMN_SIZE.lg,
    resizable: true,
    editable: true,
  },
  {
    field: "체결 가격",
    width: COLUMN_SIZE.lg,
    resizable: true,
    editable: true,
  },
  {
    field: "체결 수량",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "진입 가격",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "청산 수량",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "청산 손익",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "고객 수수료",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "체결 일시",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "전문 일자",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "전문 일련번호",
    width: COLUMN_SIZE.xl,
    resizable: true,
    editable: true,
    cellStyle: COLUMN_STYLE.right,
  },
  {
    field: "매칭엔진 ID",
    width: COLUMN_SIZE.xl,
    resizable: true,
    editable: true,
    cellStyle: COLUMN_STYLE.right,
  },
  {
    field: "외부 계좌 번호",
    width: COLUMN_SIZE.xl,
    resizable: true,
    editable: true,
    cellStyle: COLUMN_STYLE.right,
  },
  {
    field: "외부 체결 그룹 번호",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "외부 체결 번호",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "외부 주문 번호",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "MAKER 주문 여부",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "생성 작업 ID",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "증거금 가격",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "생성 작업 ID",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "생성 작업 일시",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "변경 작업 ID",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "변경 작업 일시",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
];
