import { COLUMN_SIZE, COLUMN_STYLE } from "@/app/_const/cols";
import { FieldNames } from "@/type/api";
import { ColDef } from "ag-grid-community";

export type RowData = Record<FieldNames, string>;
export const GRID_COLS: ColDef[] = [
  {
    field: "회사 코드",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "주문 일자",
    width: COLUMN_SIZE.sm,
    resizable: true,
    editable: true,
    cellStyle: COLUMN_STYLE.right,
  },
  {
    field: "주문 일련번호",
    width: COLUMN_SIZE["2xl"],
    resizable: true,
    editable: true,
    cellStyle: COLUMN_STYLE.left,
  },
  {
    field: "계좌 번호",
    width: COLUMN_SIZE["2xl"],
    resizable: true,
    editable: true,
  },
  {
    field: "종목 코드",
    width: COLUMN_SIZE.sm,
    resizable: true,
    editable: true,
  },
  {
    field: "원 주문 일자",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "원 주문 일련번호",
    width: COLUMN_SIZE["2xl"],
    resizable: true,
    editable: true,
    cellStyle: COLUMN_STYLE.right,
  },
  {
    field: "최초 주문 일자",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "최초 주문 일련번호",
    width: COLUMN_SIZE["2xl"],
    resizable: true,
    editable: true,
    cellStyle: COLUMN_STYLE.right,
  },
  {
    field: "주문 상태 구분",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "주문 구분",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "호가 구분",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "매수매도 구분",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "주문 가격 구분",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "체결 조건 구분",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "레버리지 크기",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "조건 가격",
    width: COLUMN_SIZE.xl,
    resizable: true,
    editable: true,
  },
  {
    field: "주문 가격",
    width: COLUMN_SIZE.xl,
    resizable: true,
    editable: true,
  },
  {
    field: "주문 수량",
    width: COLUMN_SIZE.xl,
    resizable: true,
    editable: true,
  },
  {
    field: "정정 수량",
    width: COLUMN_SIZE.xl,
    resizable: true,
    editable: true,
  },
  {
    field: "취소 수량",
    width: COLUMN_SIZE.xl,
    resizable: true,
    editable: true,
  },
  {
    field: "체결 수량",
    width: COLUMN_SIZE.xl,
    resizable: true,
    editable: true,
  },
  {
    field: "주문 잔량",
    width: COLUMN_SIZE.xl,
    resizable: true,
    editable: true,
  },
  {
    field: "취소 확인 수량",
    width: COLUMN_SIZE.xl,
    resizable: true,
    editable: true,
  },
  {
    field: "증거금 가격",
    width: COLUMN_SIZE.xl,
    resizable: true,
    editable: true,
  },
  {
    field: "가격 종목 코드",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "수수료 종목 코드",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "주문 만기 코드",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "주문 만기 일자",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "주문 종료 구분",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "체결 종료 여부",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "주문 접수 일시",
    width: COLUMN_SIZE.xl,
    resizable: true,
    editable: true,
  },
  {
    field: "전문 일자",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "전문 일련번호",
    width: COLUMN_SIZE["2xl"],
    resizable: true,
    editable: true,
  },
  {
    field: "외부 계좌 번호",
    width: COLUMN_SIZE["2xl"],
    resizable: true,
    editable: true,
  },
  {
    field: "외부 주문 번호",
    width: COLUMN_SIZE["2xl"],
    resizable: true,
    editable: true,
  },
  {
    field: "외부 원 주문 번호",
    width: COLUMN_SIZE["2xl"],
    resizable: true,
    editable: true,
  },
  {
    field: "거부 사유",
    width: COLUMN_SIZE.md,
    resizable: true,
    editable: true,
  },
  {
    field: "생성자",
    width: COLUMN_SIZE.xl,
    resizable: true,
    editable: true,
  },
  {
    field: "생성 일시",
    width: COLUMN_SIZE.xl,
    resizable: true,
    editable: true,
  },
  {
    field: "수정자",
    width: COLUMN_SIZE.xl,
    resizable: true,
    editable: true,
  },
  {
    field: "수정 일시",
    width: COLUMN_SIZE.xl,
    resizable: true,
    editable: true,
  },
];
